name: CI / CD - Build & Deploy

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install root dependencies
        run: npm ci

      - name: Build (root)
        # The root package.json runs Vite with the client as the root
        run: npm run build

      - name: Prepare publish directory
        run: |
          if [ -d "dist/public" ]; then PUBLISH_DIR="dist/public";
          elif [ -d "client/dist" ]; then PUBLISH_DIR="client/dist";
          elif [ -d "client/dist/public" ]; then PUBLISH_DIR="client/dist/public";
          else echo "No build output found" && exit 1; fi
          echo "publish_dir=$PUBLISH_DIR" >> $GITHUB_ENV

      - name: Smoke test publish directory
        run: |
          echo "Checking publish directory: ${{ env.publish_dir }}"
          if [ -z "${{ env.publish_dir }}" ]; then echo "publish_dir is not set" && exit 1; fi
          if [ ! -d "${{ env.publish_dir }}" ]; then echo "Publish directory does not exist: ${{ env.publish_dir }}" && ls -la && exit 1; fi
          if [ ! -f "${{ env.publish_dir }}/index.html" ]; then echo "index.html not found in publish directory: ${{ env.publish_dir }}" && ls -la "${{ env.publish_dir }}" && exit 1; fi
          echo "Smoke test passed: index.html found in ${{ env.publish_dir }}"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{ env.publish_dir }}
